# Generated by Django 4.2.6 on 2023-11-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_latin', models.CharField(max_length=60)),
                ('name_arabic', models.CharField(max_length=60)),
                ('writer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_l', models.CharField(max_length=60)),
                ('name_a', models.CharField(max_length=60)),
                ('in_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.books')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_l', models.CharField(max_length=60)),
                ('name_a', models.CharField(max_length=60)),
                ('in_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Khadises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_l', models.CharField(max_length=60)),
                ('name_a', models.CharField(max_length=60)),
                ('in_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.parts')),
            ],
        ),
    ]
