# Generated by Django 4.2.6 on 2023-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khadises',
            name='narrated_by',
            field=models.CharField(default='by Someone', max_length=100),
        ),
        migrations.AddField(
            model_name='khadises',
            name='status',
            field=models.CharField(default='Sahih', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='name_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='name_l',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='khadises',
            name='name_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='khadises',
            name='name_l',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parts',
            name='name_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parts',
            name='name_l',
            field=models.CharField(max_length=100),
        ),
    ]
