# Generated by Django 4.2.6 on 2023-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0002_khadises_narrated_by_khadises_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khadises',
            old_name='name_a',
            new_name='name_ara',
        ),
        migrations.RenameField(
            model_name='khadises',
            old_name='name_l',
            new_name='name_lat',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='name_a',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='name_l',
            new_name='name_la',
        ),
    ]
