# Generated by Django 4.2.6 on 2023-11-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0003_rename_name_a_khadises_name_ara_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Khadises',
            new_name='T_Khadises',
        ),
    ]
